services:
  next:
    image: node:22
    container_name: next
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Empêche les conflits entre hôte et conteneur
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://$DB_USER_LOGIN:$DB_USER_PWD@postgres:5432/mydb
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER_LOGIN
      POSTGRES_PASSWORD: $DB_USER_PWD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
