import { dosis } from '@/scss/fonts';
import type { Metadata } from 'next';
import '../scss/global.css';
import '../scss/theme.scss';
import SessionProviderComponent from './SessionProviderComponent';

export const metadata: Metadata = {
  title: 'Entropia Manager',
  description: 'Generated by David',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" style={dosis.style}>
      <body>
        <SessionProviderComponent>{children}</SessionProviderComponent>
      </body>
    </html>
  );
}
