import type { Metadata } from 'next';
import { dosis } from '../styles/fonts.js';
import '../styles/global.css';
import ReactQueryProvider from './ReactQueryProvider';
import SessionProviderComponent from './SessionProviderComponent';
// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Entropia Manager',
  description: 'Generated by David',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" style={dosis.style}>
      <body>
        <SessionProviderComponent>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </SessionProviderComponent>
      </body>
    </html>
  );
}
